#!/usr/bin/env bash
# PreToolUse(Edit|Write|NotebookEdit): protect generated + append-only files.
set -uo pipefail

input="$(cat)"
path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // ""' 2>/dev/null)"
[ -z "$path" ] && exit 0

# Resolve a repo-relative path. CLAUDE_PROJECT_DIR is set by Claude Code; fall
# back to the git root so the hook is testable and correct when run standalone.
root="${CLAUDE_PROJECT_DIR:-}"
if [ -z "$root" ]; then
  root="$(git -C "$(dirname "$path")" rev-parse --show-toplevel 2>/dev/null || pwd)"
fi
rel="${path#"$root"/}"

deny() { printf 'Blocked by fiber toolkit: %s\n' "$1" >&2; exit 2; }

case "$rel" in
  crates/fiber-core/migrations/*.sql)
    # Only block files that are already committed; a brand-new migration is fine.
    if git -C "${CLAUDE_PROJECT_DIR:-.}" ls-files --error-unmatch "$rel" >/dev/null 2>&1; then
      next="$(ls "${CLAUDE_PROJECT_DIR:-.}"/crates/fiber-core/migrations/ 2>/dev/null | tail -1)"
      deny "$rel is an applied sqlx migration. sqlx checksums it at fiber-api boot, so editing it breaks every existing database.
Create the next numbered file instead (highest today: ${next:-none}). See the fiber-migration skill."
    fi
    ;;
  apps/web/src/routeTree.gen.ts)
    deny "routeTree.gen.ts is generated by the TanStack Router plugin. Add or rename a file in apps/web/src/routes/ and let 'pnpm dev' regenerate it."
    ;;
  data/*|apps/web/dist/*|target/*|Cargo.lock)
    deny "$rel is generated or runtime state, not source. data/ holds dev artifacts and agent git workspaces; Cargo.lock changes only via cargo."
    ;;
esac

exit 0
