/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdAgentsRouteImport } from './routes/p.$projectId.agents'
import { Route as PProjectIdFibersRouteImport } from './routes/p.$projectId.fibers'
import { Route as PProjectIdPipelinesPipelineIdRouteImport } from './routes/p.$projectId.pipelines.$pipelineId'
import { Route as PProjectIdRunsRunIdRouteImport } from './routes/p.$projectId.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdAgentsRoute = PProjectIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdFibersRoute = PProjectIdFibersRouteImport.update({
  id: '/fibers',
  path: '/fibers',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdPipelinesPipelineIdRoute =
  PProjectIdPipelinesPipelineIdRouteImport.update({
    id: '/pipelines/$pipelineId',
    path: '/pipelines/$pipelineId',
    getParentRoute: () => PProjectIdRoute,
  } as any)
const PProjectIdRunsRunIdRoute = PProjectIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => PProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/agents': typeof PProjectIdAgentsRoute
  '/p/$projectId/fibers': typeof PProjectIdFibersRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/pipelines/$pipelineId': typeof PProjectIdPipelinesPipelineIdRoute
  '/p/$projectId/runs/$runId': typeof PProjectIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/p/$projectId/agents': typeof PProjectIdAgentsRoute
  '/p/$projectId/fibers': typeof PProjectIdFibersRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/pipelines/$pipelineId': typeof PProjectIdPipelinesPipelineIdRoute
  '/p/$projectId/runs/$runId': typeof PProjectIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/agents': typeof PProjectIdAgentsRoute
  '/p/$projectId/fibers': typeof PProjectIdFibersRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/pipelines/$pipelineId': typeof PProjectIdPipelinesPipelineIdRoute
  '/p/$projectId/runs/$runId': typeof PProjectIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/login'
    | '/settings'
    | '/p/$projectId'
    | '/p/$projectId/agents'
    | '/p/$projectId/fibers'
    | '/p/$projectId/'
    | '/p/$projectId/pipelines/$pipelineId'
    | '/p/$projectId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/login'
    | '/settings'
    | '/p/$projectId/agents'
    | '/p/$projectId/fibers'
    | '/p/$projectId'
    | '/p/$projectId/pipelines/$pipelineId'
    | '/p/$projectId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/login'
    | '/settings'
    | '/p/$projectId'
    | '/p/$projectId/agents'
    | '/p/$projectId/fibers'
    | '/p/$projectId/'
    | '/p/$projectId/pipelines/$pipelineId'
    | '/p/$projectId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/agents': {
      id: '/p/$projectId/agents'
      path: '/agents'
      fullPath: '/p/$projectId/agents'
      preLoaderRoute: typeof PProjectIdAgentsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/fibers': {
      id: '/p/$projectId/fibers'
      path: '/fibers'
      fullPath: '/p/$projectId/fibers'
      preLoaderRoute: typeof PProjectIdFibersRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/pipelines/$pipelineId': {
      id: '/p/$projectId/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/p/$projectId/pipelines/$pipelineId'
      preLoaderRoute: typeof PProjectIdPipelinesPipelineIdRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/runs/$runId': {
      id: '/p/$projectId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/p/$projectId/runs/$runId'
      preLoaderRoute: typeof PProjectIdRunsRunIdRouteImport
      parentRoute: typeof PProjectIdRoute
    }
  }
}

interface PProjectIdRouteChildren {
  PProjectIdAgentsRoute: typeof PProjectIdAgentsRoute
  PProjectIdFibersRoute: typeof PProjectIdFibersRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
  PProjectIdPipelinesPipelineIdRoute: typeof PProjectIdPipelinesPipelineIdRoute
  PProjectIdRunsRunIdRoute: typeof PProjectIdRunsRunIdRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdAgentsRoute: PProjectIdAgentsRoute,
  PProjectIdFibersRoute: PProjectIdFibersRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
  PProjectIdPipelinesPipelineIdRoute: PProjectIdPipelinesPipelineIdRoute,
  PProjectIdRunsRunIdRoute: PProjectIdRunsRunIdRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
